networks:
  portainer:
    external: true
services:
    alist:
        image: 'jianhua123/telegram-backup:latest'
        container_name: tgbackup
        restart: unless-stopped
        volumes:
            - /root/containers/tgbackup/data:/app/data
        environment:
            - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
            - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
            - BACKUP_DELAY=${BACKUP_DELAY}
        networks:
            - portainer
